GET http://localhost:3000
Content-Type: application/json

###

POST http://localhost:3000
Content-Type: application/json

{
  "entity": "teacher",
  "name": "sandra",
  "lastName": "sei la",
  "document": "3454",
  "phone": "519969894156",
  "email": "@",
  "hiringDate": "15/153/156",
  "specialization": "história",
  "groupsIds": ["1"]
}