POST http://localhost:3000
Content-Type: application/json

{
  "entity": "groups",
  "teacherId": "II412",
  "studentsIds": ["GJ958", "OB088", "IS530"]
}

###

GET http://localhost:3000
Content-Type: application/json

###

PUT http://localhost:3000
Content-Type: application/json

{
  
}

###

DELETE http://localhost:3000
Content-Type: application/json

{
  "entity": "groups",
  "id": "GY161"
}