GET http://localhost:3000
Content-Type: application/json

###

POST http://localhost:3000
content-type: application/json

{
  "entity": "student",
  "name": "Tanubinha",
  "lastName": "Mendes",
  "birthDay": "25/08/1992",
  "parents": ["3"],
  "allergies": [""],
  "blood": "A-",
  "medicines": [],
  "registrationDate": "01/03/1999",
  "document": "",
  "groups": ""
}